safe:        true

title:       "Service Design Manual"
baseurl:     
username:    GuildfordBC

source:      ./
destination: ./_site
future:      true
lsi:         false
highlighter: pygments
markdown:    kramdown
permalink:   pretty

exclude:
  - compile.sh
  - CONTRIBUTING.md
  - Gemfile
  - Gemfile.lock
  - Makefile
  - lint.go
  - README.md
  - tools
  - vendor

rdiscount:
  extensions: []

kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true

  coderay:
    coderay_wrap: div
    coderay_line_numbers: ''
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style
